language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: YZNn2tKxC0JfkQPF4JKa+PJFuQ2gwXHrkYzXojc58h9UkJMCD85j6tq9eC46U783FDYZofs3AcA/qpQZINF1UknpZx6ESO72zAPshay4XC8arebBsgg9zT7zmX9eFoEVbjweYcWh5Wgw/OuASOfVfRgo93hnSiqnmi+roxG2EP1CPVRPmN3QPbBRe4yijCUnQgL2pfyeAtbqe3IJ4OEL/YWgsiquAWZr6IxBsxD17IfZh/oxEkTzj6Q9eA9uuDfmRAWzl6e1puOyOG2GaHPSWFY+SjFgAjN8WU3iA3t/YIicXqwRam4Nr7UsJhGE+eCkwewe/gM1vq6Ot+cAuxopbrlNwhCoWi499WSaU64+p/KsLMWRwU68d/IFKM8krH8iBDOBpiogPWj/Wemk6EujR4Tv2EpPxY2gDbWe0sNYZPGdYY71YrEZ19I2cS4wB6yVodMrcPYiiySID977pPV8KIuzdJl5C/r7OWhI5eJAWBel/eZLGvj+58jsgziwecuXLb5n0BaTnZL1U8q5xeLl0PtlWEATVgCy7SIjExWPVoD8AZnw/HnioKpuuEdl35yH63yt9TGnYrpS8BtOaqqhiRYkAuR5VKSfLW4hNFpxVdkQzZENMG/Adox1sNq3rgl9dAO4jae+vdDo/HMaiwozuaWajefCIuISiLzsEFpgvho=
  app: secret-garden-14097
